apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: MONGODB_CONN
              valueFrom:
                secretKeyRef:
                  name: mongo-conn-secret
                  key: mongo-conn
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri-secret
                  key: mongo-uri
          resources:
            requests:
              cpu: {{ .Values.backend.cpu }}
            limits:
              cpu: {{ .Values.backend.memory }}
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}