apiVersion: v1
kind: Secret
metadata:
  name: mongo-conn-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongo-conn: {{ .Values.mongoSecrets.conn }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-uri-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongo-uri: {{ .Values.mongoSecrets.uri }}
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: recipetracker
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerSecrets.conn }}