apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: recipetracker
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJub2VsbWNrZW93biIsInBhc3N3b3JkIjoiTGV4YWNvbkAxMCIsImVtYWlsIjoibm9lbG1ja2Vvd25AZ21haWwuY29tIiwiYXV0aCI6ImJtOWxiRzFqYTJWdmQyNDZUR1Y0WVdOdmJrQXhNQT09In19fQ==