apiVersion: v1
kind: Secret
metadata:
  name: mongo-conn-secret
  namespace: recipetracker
type: Opaque
data:
  mongo-conn: bW9uZ29kYitzcnY6Ly9ub2VsbWNrZW93bjo2QXlMSFlHa29jbzFAZW50LWFyY2gtZGVwbG95LWNhMi1tb24uYm5vZmVmZy5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9ZW50LWFyY2gtZGVwbG95LWNhMi1tb25nbw==
  
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-uri-secret
  namespace: recipetracker
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly9ub2VsbWNrZW93bjo2QXlMSFlHa29jbzFAZW50LWFyY2gtZGVwbG95LWNhMi1tb24uYm5vZmVmZy5tb25nb2RiLm5ldC8=
