apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
  namespace: recipetracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-green
  template:
    metadata:
      labels:
        app: frontend-green
    spec:
      containers:
        - name: frontend
          image: noelmckeown/frontend:green
          ports:
            - containerPort: 9000
          env:
            - name: BACKEND_HOST
              value: backend
            - name: BACKEND_PORT
              value: "8080"
            - name: FRONTEND_PORT
              value: "22137"
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
      imagePullSecrets:
        - name: regcred